### ISSUE TITLE
crawl echemportal

### ISSUE THREAD

**Issue by tomlue** [biobricks-ai/biobricks-issues#21]
the echemportal search allows wildcards, we could iterate through legal cas that way:
00*
10*
11*
12*
etc.

Let's try to be polite, no massively parallel crawling or anything.

**Comment by john-shaffer** [comment]
Completed in [32d702cd265ecc9ed0d50ee3adb0f1cf04125e71](https://github.com/biobricks-ai/echemportal/commit/32d702cd265ecc9ed0d50ee3adb0f1cf04125e71)
