### ISSUE TITLE
KG vs data bricks - define in README

### ISSUE THREAD

**Issue by karafecho** [biobricks-ai/biobricks-issues#25]
This issue is to suggest that the README [here](https://github.com/biobricks-ai/biobricks) includes a description of what the difference is between, e.g., ctdbase and ctdbase-kg, perhaps after this statement: "To list the bricks currently available visit [github.com/biobricks-ai](https://github.com/biobricks-ai)".

**Comment by tomlue** [comment]
We will handle this on status.biobricks.ai with tags that describe what kind of asset is being distributed by a given brick.
