### ISSUE TITLE
Remove case sensitivity

### ISSUE THREAD

**Issue by karafecho** [biobricks-ai/biobricks-issues#26]
When installing biobricks, there are several decision points where users are asked to choose between "yes" and "no", often presented as "y/N". Suggest removing the case sensitivity, as it is not necessary and rather annoying.

**Comment by tomlue** [comment]
It looks like the prompt is not case sensitive. I tested for y,Y,Yes,yes and n,N,No,no. Are you suggesting just to change the displayed prompt? We can do that, but I want to be sure that is the issue and not something else.

If that is the case, what would you like the displayed prompt to be?

**Comment by karafecho** [comment]
Hmmm. The issue I encountered was directly related to case sensitivity. If I recall correctly, I had entered "n" when prompted, but that wasn't recognized, so I tried "N", which worked.

I guess maybe change the display prompt for now and see if the issue surfaces again?

**Comment by tomlue** [comment]
I think this should be resolved with our recent updates.
