### ISSUE TITLE
Example code snippets need updating and should be provided in both R and Python

### ISSUE THREAD

**Issue by karafecho** [biobricks-ai/biobricks-issues#27]
This issue is to suggest that example code snippets be reviewed and updated as needed. I did not document broken code examples, but I ran into enough issues to convince me that the examples require a systematic review by a developer. Moreover, the examples alternate between R and Python, which is confusing to users. Suggest providing examples in both R and Python.

**Comment by tomlue** [comment]
Updated docs.biobricks.ai has R and python example now. 

![image](https://github.com/biobricks-ai/biobricks-issues/assets/1987278/edabd73a-3589-40da-a0ce-7f04cf75e2d7)
