### ISSUE TITLE
Brick descriptions are missing or could be improved

### ISSUE THREAD

**Issue by karafecho** [biobricks-ai/biobricks-issues#28]
This issue is to note that brick descriptions are sometimes missing (no README), e.g., [ctdbase-kg](https://github.com/biobricks-ai/ctdbase-kg) and [biobricks-closure](https://github.com/biobricks-ai/biobricks-clojure) (although perhaps this isn't a brick?), or somewhat incomplete, e.g., [bindingdb](https://github.com/biobricks-ai/bindingdb) and [hgnc](https://github.com/biobricks-ai/hgnc). In addition, important things like versioning and licensing information are missing.

Here's an example description of a "knowledge source" that I provided for another project (ROBOKOP):

![image](https://github.com/biobricks-ai/biobricks-issues/assets/26254388/c1c25bc5-d5bd-4c89-8f96-cd04d09f482e)

Here's an example description of a "knowledge source" that I provided for a different project (Translator):

![image](https://github.com/biobricks-ai/biobricks-issues/assets/26254388/d1e896c0-5bff-4246-89e6-667a7f77de60)

Suggest considering more templated and complete descriptions. I can help with this after I am more familiar with BioBricks, the repo, etc.

**Comment by tomlue** [comment]
This is now tracked on status.biobricks.ai. I'm going to close this issue and we will focus on addressing all of the unhealth bricks there. 

![image](https://github.com/biobricks-ai/biobricks-issues/assets/1987278/e2cb6404-0acd-48c6-85c1-88bb0b6e355b)
