### ISSUE TITLE
RefSeq

### ISSUE THREAD

**Issue by jborden** [biobricks-ai/biobricks-issues#4]
https://ftp.ncbi.nlm.nih.gov/refseq/

**Comment by jborden** [comment]
The total size of this dataset is:
```
$ echo "du -hs ." | lftp ftp://ftp.ncbi.nlm.nih.gov/refseq/ 2>&1
6.3T    .
```
on ws2:
```
$ df -h
...
/dev/md0         11T  1.6T  9.3T  15% /mnt/raid
```
I don't think we would have enough room to even process this dataset

**Comment by tomlue** [comment]
yep, this one is too big for now :) goal for the future maybe
