### ISSUE TITLE
stringDB

### ISSUE THREAD

**Issue by jborden** [biobricks-ai/biobricks-issues#7]
https://string-db.org/cgi/download?sessionId=bnTKutRFqrJe Huge database, could be data overlap (between INTERACTION DATA/ ACCESSORY DATA and FULL DATABASE DUMPS)

**Comment by achatrath** [comment]
I'll try this one. I think the files can be filtered down to a manageable size if we restrict the data to humans. The full database has data on many organisms so the size of the full database is likely not feasible for us.

**Comment by achatrath** [comment]
This brick runs now:

library(biobricks)
brick_install("stringDB")
brick_pull("stringDB")
brick_load_arrow("stringDB")
